--- # LOOP Playbook Example
- hosts: web-group
  user: prad
  sudo: yes
  connection: ssh
  tasks:
  - name: Add a list of users
    user: name={{item}} state=present
    with_items:
    - user1
    - user2
    - user3
